---
version: "3"
services:
  marax-adapter:
    #build: .
    image: laebshade/marax-adapter
    container_name: maraxadapter
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - marax-storage:/var/log/marax
    restart: always
  telegraf:
    image: telegraf
    container_name: telegraf
    depends_on:
      - marax-adapter
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - marax-storage:/var/log/marax
    restart: always
volumes:
  marax-storage:
