{
 "title": "Overview",
 "description": "Mara X Temperatures",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Mode",
   "type": "stat",
   "description": "Brew or steam mode indicator",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Mode",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mode-version::field" ], "type": "tag" }
     ],
     "measurement": "tail",
     "select": [
      [
       { "params": [ "mode-version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heat Modes",
   "type": "stat",
   "description": "State of heating element in the steam boiler and what brew/steam mode; it can be on, off or standby or low, normal, high, or steam, respectively.",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Thermal coil",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT floor(((mode(\"heatOn\") + 1) * median(\"steamTempTarget\")) / 100) FROM \"tail\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "heatOn" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    },
    {
     "alias": "Mode",
     "groupBy": [
      { "params": [ "mode-version::field" ], "type": "tag" }
     ],
     "measurement": "tail",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "mode-version" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Exchanger Now",
   "type": "gauge",
   "description": "Latest temperature from the heat exchanger",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT last(\"exchangerTempActual\") FROM \"tail\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "exchangerTempActual" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Steam Now",
   "type": "gauge",
   "description": "Latest temperature from the steam wand",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Actual Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT last(\"steamTempActual\") FROM \"tail\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "exchangerTempActual" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Target Temp",
     "query": "SELECT last(\"steamTempTarget\") FROM \"tail\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Exchanger History",
   "type": "timeseries",
   "description": "Temperature recorded by heat exchanger probe",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "alias": "Exchanger °C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT last(\"exchangerTempActual\") FROM \"tail\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "exchangerTempActual" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Steam Boiler",
   "type": "timeseries",
   "description": "Target and actual temperatures from steam boiler probe",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "alias": "Steam °C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "select": [
      [
       { "params": [ "steamTempActual" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Target °C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "select": [
      [
       { "params": [ "steamTempTarget" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fast Heating",
   "type": "timeseries",
   "description": "Count down of time heating element will remain on for",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Mode",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "select": [
      [
       { "params": [ "fastHeating" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}